### PR TITLE
Update two more variables in soil adjustment:

### PR DESCRIPTION
**Pull request by hu5970**
Update two more variables in soil adjustment  
  qwv_surf_land and clw_surf_land,
which are mixing ratio of water vapor and cloud water at the surface

### CODE REVIEW

**Review by tanyasmirnova — APPROVED** [review]
This modification will produced a more consistent initial state at the surface, that will improve the verification at 0 hour. The impact will be diminishing towards 1-h forecast.

**Comment by daviddowellNOAA** [comment]
Ming and Tanya:  Thanks for improving the soil adjustment.  Have these changes been tested (apply adjustment, run forecast) with at least a single case?

**Comment by hu5970** [comment]
@daviddowellNOAA Yes, the code was test with a case and the forecast was made to check the impact with the same case.

**Comment by daviddowellNOAA** [comment]
Excellent, thanks!

**Review by daviddowellNOAA — APPROVED** [review]

**Comment by hu5970** [comment]
@daviddowellNOAA Thanks

**Pull request merged**
