### PR TITLE
[production/RRFS.v1] adds bucket code for 15 minute QPF, cleans up legacy makefiles

### PR DESCRIPTION
**Pull request by MatthewPyle-NOAA**
## DESCRIPTION OF CHANGES:

Adds new rrfs_bucket.fd code.  It probably isn't in final form, but want to get it established within rrfs_utl.  Also cleaned out some legacy makefiles from the pre-cmake build system for the bufrsnd codes.

## TESTS CONDUCTED:

Confirmed that it all builds, and confirmed that the rrfs_bucket executable built from this rrfs_utl could run a simple offline test script of the bucket processing.

## ISSUE (optional):

Partially resolves this [issue](https://github.com/NOAA-GSL/rrfs_utl/issues/60).

### CODE REVIEW

**Review by christopherwharrop-noaa — CHANGES_REQUESTED** [review]
Thank you for this update and especially for removing the obsolete makefiles.  My only request is in regards to the `bucket_diff.f` file being added.  The coding style does not incorporate proper indentation for conditionals and loops and is very inconsistent throughout.  As a result the code is very hard to read and understand. 
 Since this is a new addition, it would be nice to have that cleaned up at the start.  Could you please add consistent indentation for that new code?

**Comment by MatthewPyle-NOAA** [comment]
@christopherwharrop-noaa Good suggestion - did some formatting cleanup.  Let me know if that wasn't enough.

**Review by christopherwharrop-noaa — APPROVED** [review]
Thank you very much for fixing the indentation.  That is a huge improvement that makes the code a lot easier to look at.

**Comment by MatthewPyle-NOAA** [comment]
Will have another commit for this one - my updated code had an error preventing it from compiling.  Once I confirm that this problem is resolved, will push another change.

**Pull request merged**
