### PR TITLE
developing CI system

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #33 

Continued development of CI system...

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@christinaholtNOAA and/or @christopherwharrop-noaa you need to approve the running of tests the first few times for my PRs.

I think after you approve of two of my PRs running tests, it will assume your approval for future PRs.

**Comment by christopherwharrop-noaa** [comment]
@edwardhartnett - I changed the setting from "require approval for all outside collaborators" to "require approval for first time contributors".  You should be good to go now.

**Comment by edwardhartnett** [comment]
When fetching the GSI submodules I get this set of errors. @christopherwharrop-noaa any idea what is going on?

  /usr/bin/git submodule sync --recursive
  /usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
  Submodule 'fix' (gerrit:GSI-fix) registered for path 'fix'
  Submodule 'libsrc' (gerrit:GSI-libsrc) registered for path 'libsrc'
  Cloning into '/home/runner/work/rrfs_utl/rrfs_utl/gsi/fix'...
  ssh: Could not resolve hostname gerrit: Temporary failure in name resolution
  Error: fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  Error: fatal: clone of 'gerrit:GSI-fix' into submodule path '/home/runner/work/rrfs_utl/rrfs_utl/gsi/fix' failed
  Failed to clone 'fix'. Retry scheduled
  Cloning into '/home/runner/work/rrfs_utl/rrfs_utl/gsi/libsrc'...
  ssh: Could not resolve hostname gerrit: Temporary failure in name resolution
  Error: fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  Error: fatal: clone of 'gerrit:GSI-libsrc' into submodule path '/home/runner/work/rrfs_utl/rrfs_utl/gsi/libsrc' failed
  Failed to clone 'libsrc'. Retry scheduled
  Cloning into '/home/runner/work/rrfs_utl/rrfs_utl/gsi/fix'...
  ssh: Could not resolve hostname gerrit: Temporary failure in name resolution
  Error: fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  Error: fatal: clone of 'gerrit:GSI-fix' into submodule path '/home/runner/work/rrfs_utl/rrfs_utl/gsi/fix' failed
  Failed to clone 'fix' a second time, aborting
  Error: The process '/usr/bin/git' failed with exit code 1

**Comment by christopherwharrop-noaa** [comment]
@edwardhartnett - I think it's because of the tag you are checking out.  GSI had submodules that pointed to VLab which is not publicly accessible.  For rrfs_utl, I think you need to be using `develop` and not the `gefs` tag.

**Comment by christopherwharrop-noaa** [comment]
In fact, I can guarantee you that won't work because that tag is from 2020.  The rrfs_utl CMake relies on a lot of GSI build system refactoring that happened a long time after that. Also, RRFS in general (which uses the rrfs_utl library collection) needs `develop` because GSL has contributed a lot of very recent updates.

**Comment by edwardhartnett** [comment]
@christopherwharrop-noaa when building GSI for this, I need crtm. Should I get that from the NCEPLIBS-crtm? Or elsewhere?

**Comment by christopherwharrop-noaa** [comment]
@edwardhartnett - I'm not sure.  It's been a while since I dealt with the rrfs_utl and GSI build.  I'd guess that the NCEPLIBS one is fine, but I'd have to dig a bit to get a definitive answer.

**Comment by christopherwharrop-noaa** [comment]
Rahul Mahajan may know.  I'd tag him here, but he's not on this repo or org.

**Comment by edwardhartnett** [comment]
OK, currently having trouble building GSI.

@christopherwharrop-noaa and @christinaholtNOAA would it be acceptable to first do a CI system for GSI to work out the kinks of building that it GitHub actions?

**Comment by christinaholtNOAA** [comment]
@edhartnett I think this sort of thing may be getting at the heart of the problem(s) we've been facing with testing in this repo. I think it could be helpful to get a successful build prepared for GSI, but we will have to do some assessments of scope of that requirement. 

We have some options for doing this on-prem and hooking it into the repo that way, which may be one way for us to at least have the resources and compilers we'd need for that work. It just takes a bit more effort than we currently have on the project currently. I'd like to see us get there in the short-term though.

**Comment by edwardhartnett** [comment]
OK, I meant would it be OK for me to do it. ;-)

I already have everything needed in this repo's workflow file, which builds all the GSI dependencies...

There is also another way to do this, based spack, that is much more compact and easy to manage. I will try that was well. But in either case, I need to build GSI first...

**Pull request closed without merging**
