### PR TITLE
Add firewx_gridspecs source code to rrfs_utl

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES:

The RRFS fire weather nest will be implemented with RRFS version 1, and it is designed to replicate the current capability of the operational NAM fire weather nest.  A source code called firewx_gridspecs is needed in order to read in a latlons_corners text file (produced by the UPP), and it creates the WGRIB2 grid specs for the fire weather output grid.

## TESTS CONDUCTED:

Successfully built the firewx_gridspecs source code on Hera and WCOSS2.

## DEPENDENCIES:

This code is needed for a future PR to rrfs-workflow for adding the RRFS fire weather nest post-processing capability.

## DOCUMENTATION:

Let me know if I need to add any documentation with this PR.

## ISSUE (optional):

Related to issue 15 in the rrfs-workflow repository:
https://github.com/NOAA-EMC/rrfs-workflow/issues/15

## CONTRIBUTORS (optional):

I am not too familiar with using cmake, so I followed what @MatthewPyle-NOAA did for the RRFS bufr codes in the bufrsnd directory.

### CODE REVIEW

**Review by christopherwharrop-noaa — CHANGES_REQUESTED** [review]
Can you please remove the `makefile`?  This repository uses a CMake build system.

**Comment by BenjaminBlake-NOAA** [comment]
Sure no problem, I just removed the makefile.  A few other directories here contain makefiles, specifically bufrsnd.fd/rrfs_bufr.fd, bufrsnd.fd/rrfs_sndp.fd, bufrsnd.fd/rrfs_stnmlist.fd, and lightning.fd, so I wonder if those are also not needed and could be removed.

**Comment by christopherwharrop-noaa** [comment]
Thank you @BenjaminBlake-NOAA .  Thank you for pointing those other makefiles out.  They should also be removed, but aren't really in the scope of this PR.

**Review by christopherwharrop-noaa — APPROVED** [review]
Thank you for addressing my concern.

**Comment by BenjaminBlake-NOAA** [comment]
@christopherwharrop-noaa No problem, thanks for taking the time to review.

**Review by guoqing-noaa — APPROVED** [review]

**Pull request merged**
