### PR TITLE
added developer workflow

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #33

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Repo manager has to turn on CI with GitHub actions.

**Comment by edwardhartnett** [comment]
IIRC the way to turn on GitHub actions is to merge this PR, adding a YML file in the .github/workflows directory...

**Comment by christopherwharrop-noaa** [comment]
To clarify, you will submit multiple PRs which will collectively address #33 and this one is just the first one?  Here it looks like the CI is just installing a couple system packages and installing/building `bacio`, `w3emc`, and `jasper`.  The list of dependencies is pretty long, so probably a good idea to do them in batches.

**Review by christinaholtNOAA — APPROVED** [review]
Looks great to me! I'm happy to turn on Actions for this repo.

This is a nice step to help us safety check GNU compilers where we were not before.

**Comment by christopherwharrop-noaa** [comment]
@christinaholtNOAA - I already turned actions on.  But it hasn't taken effect for this PR for some reason.

**Comment by christinaholtNOAA** [comment]
I think it will have to be merged first.

**Review by christopherwharrop-noaa — APPROVED** [review]
It's hard to do an eyeball test of a CI workflow, but we seem to have a chicken and egg problem getting the CI to turn on, so will approve to initiate that.

**Comment by christinaholtNOAA** [comment]
Unfortunately, I haven't run across any other great way to fully test a GHA workflow.

**Comment by edwardhartnett** [comment]
@christopherwharrop-noaa as indicated this is only "part of" #33.

It's best to develop the CI system in iterations. But the CI won't start running until we get the first one merged to develop. ;-)

So merge this partial CI workflow, and I will fill in the rest, and let the workflow run as I do so to ensure that it's working.

The list of dependencies is long but not much longer than we already handle for UFS_UTILS. Once we get up and running I will demonstrate how we can test against different versions of the dependencies.

**Comment by christopherwharrop-noaa** [comment]
The CI is running now after I merged it.  We should be good to go for the next iteration.  Thanks!

**Pull request merged**
